// Code generated by "stringer -type=ttype"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tillegal-0]
	_ = x[tnum-1]
	_ = x[tstring-2]
	_ = x[tplus-3]
	_ = x[tsub-4]
	_ = x[tmul-5]
	_ = x[tquo-6]
	_ = x[trem-7]
	_ = x[tassign-8]
	_ = x[tland-9]
	_ = x[tlor-10]
	_ = x[teql-11]
	_ = x[tlss-12]
	_ = x[tgtr-13]
	_ = x[tnot-14]
	_ = x[tneq-15]
	_ = x[tleq-16]
	_ = x[tgeq-17]
	_ = x[tlparen-18]
	_ = x[tlbrack-19]
	_ = x[tlbrace-20]
	_ = x[tcomma-21]
	_ = x[tperiod-22]
	_ = x[trparen-23]
	_ = x[trbrack-24]
	_ = x[trbrace-25]
	_ = x[tsemicolon-26]
	_ = x[tcolon-27]
	_ = x[tif-28]
	_ = x[telse-29]
	_ = x[tfunc-30]
	_ = x[treturn-31]
	_ = x[twhile-32]
	_ = x[tident-33]
}

const _ttype_name = "tillegaltnumtstringtplustsubtmultquotremtassigntlandtlorteqltlsstgtrtnottneqtleqtgeqtlparentlbracktlbracetcommatperiodtrparentrbracktrbracetsemicolontcolontiftelsetfunctreturntwhiletident"

var _ttype_index = [...]uint8{0, 8, 12, 19, 24, 28, 32, 36, 40, 47, 52, 56, 60, 64, 68, 72, 76, 80, 84, 91, 98, 105, 111, 118, 125, 132, 139, 149, 155, 158, 163, 168, 175, 181, 187}

func (i ttype) String() string {
	if i < 0 || i >= ttype(len(_ttype_index)-1) {
		return "ttype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ttype_name[_ttype_index[i]:_ttype_index[i+1]]
}
