// Code generated by "stringer -type=vtype"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[verr-0]
	_ = x[vnum-1]
	_ = x[vstring-2]
	_ = x[vbool-3]
	_ = x[varray-4]
	_ = x[vfunc-5]
}

const _vtype_name = "verrvnumvstringvboolvarrayvfunc"

var _vtype_index = [...]uint8{0, 4, 8, 15, 20, 26, 31}

func (i vtype) String() string {
	if i < 0 || i >= vtype(len(_vtype_index)-1) {
		return "vtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vtype_name[_vtype_index[i]:_vtype_index[i+1]]
}
